const styles = {
  container: {
    maxWidth: '1200px',
    margin: '0 auto',
    padding: '20px',
    fontFamily: 'Arial, sans-serif',
    backgroundColor: '#1e1e1e',
    color: '#e0e0e0',
    minHeight: '100vh',
  },
  title: {
    fontSize: '32px',
    fontWeight: 'bold',
    marginBottom: '20px',
    textAlign: 'center',
    color: '#61dafb',
    textShadow: '0 0 10px rgba(97, 218, 251, 0.5)',
  },
  form: {
    display: 'flex',
    marginBottom: '20px',
  },
  input: {
    flex: 1,
    padding: '12px',
    fontSize: '16px',
    backgroundColor: '#2c2c2c',
    border: '1px solid #444',
    borderRadius: '4px 0 0 4px',
    color: '#e0e0e0',
  },
  button: {
    padding: '12px 24px',
    fontSize: '16px',
    backgroundColor: '#61dafb',
    color: '#1e1e1e',
    border: 'none',
    borderRadius: '0 4px 4px 0',
    cursor: 'pointer',
    transition: 'background-color 0.3s',
  },
  finalAnswer: {
    backgroundColor: '#2c2c2c',
    padding: '20px',
    borderRadius: '8px',
    marginTop: '20px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  finalAnswerText: {
    fontSize: '20px',
    fontWeight: 'bold',
    margin: 0,
    marginBottom: '10px',
    color: '#61dafb',
  },
  popupOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  popupContent: {
    backgroundColor: '#1e1e1e',
    padding: '20px',
    borderRadius: '8px',
    maxWidth: '90%',
    maxHeight: '90%',
    overflow: 'auto',
    position: 'relative',
  },
  closeButton: {
    position: 'absolute',
    top: '10px',
    right: '10px',
    background: 'none',
    border: 'none',
    color: '#61dafb',
    fontSize: '24px',
    cursor: 'pointer',
  },
  graphContainer: {
    marginTop: '20px',
  },
  graphTitle: {
    color: '#61dafb',
    marginBottom: '15px',
  }
};

export default styles; 